version: '3.8'

services:
  server:
    container_name: clubhub-server
    build: ./server
    image: nudeli/clubhub-server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://Admin:ehiAGkcEh8508UEd@clubhub.4fw0aul.mongodb.net/ClubHub?retryWrites=true&w=majority
      - ORIGIN=http://localhost:3000
      - SESSION_SECRET=1243f23d

  client:
    container_name: clubhub-client
    build: ./client
    image: nudeli/clubhub-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000