name: Release to Docker Hub

on:
  push:
    branches:
      - docker_cd 

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}  

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: server
          push: true
          tags: nudeli/clubhub-server:latest
          build-args: |
            MONGO_URI=${{ secrets.MONGO_URI }}
            SESSION_SECRET=${{ secrets.SESSION_SECRET }}
            ORIGIN=http://localhost:3000

      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: client
          push: true
          tags: nudeli/clubhub-client:latest
          build-args: REACT_APP_API_BASE_URL=http://localhost:5000