name: Release to Docker Hub

on:
  push:
    branches:
      - docker_cd 

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}  

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v3
        with:
          username: nudeli
          password: TurnTheLightOn

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: server
          file: ./Dockerfile
          push: true
          tags: nudeli/server:latest
          build-args: MONGO_URI=${{ secrets.MONGO_URI }}  


      # - name: Build using Docker compose
      #   working-directory: ./
      #   run: docker-compose build
      #   env:
      #     MONGO_URI: ${{ secrets.MONGO_URI }} 

      # - name: Push Backend
      #   working-directory: ./
      #   run: docker push nudeli/clubhub-server

      # - name: Push Frontend
      #   working-directory: ./
      #   run: docker push nudeli/clubhub-client