name: Release to Docker Hub

on:
  push:
    branches:
      - docker_cd 

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}  

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: nudeli
          password: TurnTheLightOn

      - name: Build using Docker compose
        working-directory: ./
        run: docker-compose build
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }} 

      - name: Push Backend
        working-directory: ./
        run: docker push nudeli/clubhub-server

      - name: Push Frontend
        working-directory: ./
        run: docker push nudeli/clubhub-client